load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")

# All the default toolchains, suitable for a quick demo or early prototyping.
# Most real projects should copy/paste the implementation to configure them.
system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

load("@prelude//toolchains:python.bzl", "system_python_toolchain", "system_python_bootstrap_toolchain")

system_python_bootstrap_toolchain(name = "python_bootstrap", visibility = ["PUBLIC"])
system_python_toolchain(name = "python", visibility = ["PUBLIC"])
remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)